import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

let transporter = null;

function getTransporter() {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD
      }
    });
  }
  return transporter;
}

function generateJobHtml(job) {
  const scoreColor = job.match_score >= 7 ? '#2e7d32' : job.match_score >= 4 ? '#f57c00' : '#e57373';

  // Clean apply links - remove commas and semicolons between links
  const cleanApplyLinks = job.apply_link
    ? job.apply_link.replace(/[;,]\s*/g, ' ')
    : '';

  return `
    <div style="border-bottom: 1px solid #eee; padding: 18px 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 500px;">
            <tr>
                <td style="vertical-align: top;">
                    <div style="font-size: 14px; font-weight: 600; color: #222; margin-bottom: 3px;">${job.job_title || 'Unknown'}</div>
                    <div style="font-size: 12px; color: #777;">${job.company || 'Unknown'}</div>
                </td>
                <td width="45" style="vertical-align: top; text-align: right;">
                    <div style="width: 32px; height: 32px; background: ${scoreColor}; color: #fff; border-radius: 50%; text-align: center; line-height: 32px; font-weight: 600; font-size: 13px; display: inline-block;">
                        ${job.match_score || 0}
                    </div>
                </td>
            </tr>
        </table>
        <div style="margin-top: 8px; font-size: 11px; color: #888;">
            ${job.employment_type || 'N/A'} · ${job.remote === 'Yes' ? 'Remote' : 'On-site'}
        </div>
        <div style="margin-top: 4px; font-size: 12px; color: #2e7d32; font-weight: 500;">
            ${job.salary || 'Salary not specified'}
        </div>
        ${job.match_reason ? `
        <details style="margin-top: 10px;">
            <summary style="font-size: 11px; color: #666; cursor: pointer; outline: none;">View analysis</summary>
            <div style="margin-top: 8px; font-size: 11px; color: #555; line-height: 1.5; max-width: 480px; padding-left: 10px; border-left: 2px solid #eee;">
                ${job.match_reason}
            </div>
        </details>
        ` : ''}
        ${cleanApplyLinks ? `
        <div style="margin-top: 12px;">
            ${cleanApplyLinks.replace(/<a /g, '<a style="display: inline-block; padding: 6px 10px; background: #222; color: #fff; text-decoration: none; font-size: 10px; border-radius: 3px; margin-right: 4px; margin-bottom: 4px;" ')}
        </div>
        ` : ''}
    </div>`;
}

export async function sendJobMatchEmail(recipientEmail, jobs, threshold = 0) {
  console.log('Sending email to:', recipientEmail, 'with', jobs.length, 'jobs');

  const sortedJobs = [...jobs].sort((a, b) => b.match_score - a.match_score);

  let jobsHtml = '';
  for (const job of sortedJobs) {
    jobsHtml += generateJobHtml(job);
  }

  const htmlContent = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin: 0; padding: 24px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; background: #fff;">
    <div style="max-width: 520px;">
        <div style="margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #eee;">
            <div style="font-size: 16px; font-weight: 600; color: #222;">JobHunt</div>
            <div style="font-size: 12px; color: #999; margin-top: 2px;">${jobs.length} jobs found</div>
        </div>
        ${jobsHtml}
        <div style="margin-top: 20px; font-size: 10px; color: #ccc;">
            Generated by JobHunt
        </div>
    </div>
</body>
</html>`;

  if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) {
    throw new Error('Gmail credentials not configured');
  }

  const transport = getTransporter();
  const result = await transport.sendMail({
    from: process.env.GMAIL_USER,
    to: recipientEmail,
    subject: `JobHunt: ${jobs.length} Jobs`,
    html: htmlContent
  });

  console.log('Email sent:', result.messageId);
  return true;
}
